---
 environment: production
 chdir: /psg/webapp/s2_dev/excel_merge_service/current
 address: 127.0.0.1
 user: root
 group: root
 port: 8101
 pid: /psg/webapp/s2_dev/excel_merge_service/current/tmp/pids/thin.pid
 rackup: /psg/webapp/s2_dev/excel_merge_service/current/config.ru
 log: /psg/webapp/s2_dev/excel_merge_service/current/log/thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 daemonize: true
